version: 2
jobs:
  hygiene_tests:
    working_directory: /git/mcs-ontology
    docker:
      - image: docker/compose:debian-1.26.2
    steps:
      - run:
          name: Install official git
          command: |
            apt update && apt install -y git
      - checkout
      - setup_remote_docker
      - run:
          name: Run ontology hygiene tests
          command: |
            sh run-hygiene.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - hygiene_tests